node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  support-processing-queue {
    defaultVisibilityTimeout = 300 seconds
    delaySeconds = 0
    receiveMessageWait = 0 seconds
    fifo = true
    contentBasedDeduplication = true
  }
  support-processing-dlq {
    defaultVisibilityTimeout = 300 seconds
  }
}
