[mypy]
mypy_path = dynamodb_handler, sqs_processor
disallow_untyped_defs=True
disallow_incomplete_defs=True
show_error_codes=True
no_implicit_optional=True
ignore_missing_imports=True
files= ./dynamodb_handler/**/*.py,
       ./sqs_processor/**/*.py,
       ./tests/**/*.py
